<?php

namespace AppBundle\Repository;

/**
 * EstadoTareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoTareaRepository extends \Doctrine\ORM\EntityRepository
{
}
